トップにもどるボタン のリンク先を追加
vektor-inc/vk-all-in-one-expansion-unit pull request #1095
Opened 2024-06-21 03:37 UTC by sysbird

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
 [アクセシビリティ] トップにもどるボタン のリンク先がない問題 #1094 

## どういう変更をしたか？

* トップにもどるボタンのリンク先は #top がページ内に存在しないのは HTML5の仕様として正しいが、アクセシビリティ的に NG のため追加しました

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

#### ソースコードについて

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 はそれだけで内容が想像できるものになっているか？紛らわしい命名になっていないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 は既存のコードの命名規則に沿ったものになっているか？

#### デザイン・UI

- [ ] 初見のユーザーが予備知識無しで使っても使いやすいようになっているか？
- [ ] 情報意味を考慮した意味グルーピング・余白になっているか？
- [ ] アラートの表示など追加した場合は他の同様の表示と同じデザインになっているか？

#### プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。
書いていない場合は書かない理由を記載してください。

- [ ] 書けそうなテストは書いたか？
- [ ] 表示要素が仕様通りに表示されない不具合の修正ではない or 表示要素に関する不具合修正の場合テストは書いたか？

#### その他

- [ ] readme.txt に変更内容は書いたか？
- [ ] Files changed (変更ファイル)の内容は目視でちゃんと確認したか？
- [ ] このチェック項目を機械的にチェックするのではなく本当にちゃんと確認をしたか？
- [ ] レビュワーが確認しないでリリースしてしまっても問題ないレベルまでちゃんと作りこみ・確認をしたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーの確認方法・確認する内容など

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2024-06-21 06:34 UTC, drill-lancer commented
@sysbird 
テスト通りました。

2024-06-24 06:55 UTC, drill-lancer commented
@sysbird 
npm run build を修正しても反映されなかったので gulp のバージョンを下げたら反映されました。

---

２人目確認お願いします。

2024-07-01 21:02 UTC, kurudrive requested changes

2024-07-01 21:02 UTC, kurudrive commented on inc/pagetop-btn/js/pagetop-btn.js
> +		}
@sysbird ありがとうございます。id は一意なのでCSSのように複数入れる事はHTMLの仕様に反します。
idが既に存在する場合は、そのidを pagetop のリンク先に反映させるなどの対策をよろしくお願いいたします。

2024-07-02 01:08 UTC, sysbird commented
@kurudrive 
確認ありがとうございます
そうですね、
となると #top がどこかで使われてないか？も確認必要そう、
ややこしい〜検討します！

2024-07-26 03:35 UTC, sysbird commented
@kurudrive 
修正しました！
お手数ですが、ご確認よろしくお願いします

2024-07-29 11:33 UTC, kurudrive commented on inc/pagetop-btn/js/pagetop-btn.js
> +		}
@sysbird id は1単語のみの前提で書き換えました（複数入ってる事自体が間違いなのでその対応処理は削除）。

2024-07-29 11:35 UTC, kurudrive approved these changes
@sysbird トップに戻ると関係ないブロックのビルドがコミットに含まれているので、nodeのバージョン変更した都合だと思いますが、コミットに含めないようによろしくお願いいたしますー (￣人￣)

2024-07-29 11:40 UTC, merged