【確認待ち】XSS 潰し
vektor-inc/vk-all-in-one-expansion-unit pull request #1101
Opened 2024-07-25 03:50 UTC by drill-lancer

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1100

## どういう変更をしたか？

- ウィジェット
- CTA
- カスタム投稿タイプマネージャー

上記に潜んでいた XSS を潰しました

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

#### ソースコードについて

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 はそれだけで内容が想像できるものになっているか？紛らわしい命名になっていないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 は既存のコードの命名規則に沿ったものになっているか？

#### デザイン・UI

- [ ] 初見のユーザーが予備知識無しで使っても使いやすいようになっているか？
- [ ] 情報意味を考慮した意味グルーピング・余白になっているか？
- [ ] アラートの表示など追加した場合は他の同様の表示と同じデザインになっているか？

#### プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。
書いていない場合は書かない理由を記載してください。

- [ ] 書けそうなテストは書いたか？
- [ ] 表示要素が仕様通りに表示されない不具合の修正ではない or 表示要素に関する不具合修正の場合テストは書いたか？

#### その他

- [ ] readme.txt に変更内容は書いたか？
- [ ] Files changed (変更ファイル)の内容は目視でちゃんと確認したか？
- [ ] このチェック項目を機械的にチェックするのではなく本当にちゃんと確認をしたか？
- [ ] レビュワーが確認しないでリリースしてしまっても問題ないレベルまでちゃんと作りこみ・確認をしたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

上記の input[type="text"] に `"><script>alert(0)</script>` を入れてアラートが出ないのを確認しました。

## 確認URL

ローカル環境

## レビュワーの確認方法・確認する内容など

- 上記の input[type="text"] に `"><script>alert(0)</script>` を入れてアラートが出ないこと。
- それぞれのエスケープ手段が適切か

上記の確認をお願いします。

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2024-07-25 09:19 UTC, mthaichi reviewed
@drill-lancer ご対応ありがとうございます！
とりあえず１点気づいたことをコメントします。

2024-07-25 09:19 UTC, mthaichi commented on inc/contact-section/contact-section.php
> -		$option['contact_txt']       = stripslashes( $option['contact_txt'] );
@drill-lancer この部分でstripslashesを削除しているので、例えば Vektor's といった文字列を保存しようとすると、バックスラッシュがテキストエリアに残り、それに気づかず保存すると、倍々にバックスラッシュが増えてしまいます。

ご存知のことかもしれませんが、
WordPressは $_POSTに対して、add_magic_quotes()をかけます。$_POSTには Vektor\\'s という値で入ってきます。ですから、これに対して、wp_unslashやstripslashesで戻す処理は必要かと。

2024-07-25 10:10 UTC, mthaichi commented on inc/contact-section/contact-section.php
> -		$option['contact_txt']       = stripslashes( $option['contact_txt'] );
補足すると、CTA関連でも同様の修正がありますが、update_metadata 内で、wp_unslashが自動的にかかるので処理不要です。こちらはstripslashesを外して正解だと思います。

2024-07-29 02:11 UTC, drill-lancer commented on inc/contact-section/contact-section.php
> -		$option['contact_txt']       = stripslashes( $option['contact_txt'] );
@mthaichi 
stripslashes はエスケープには関係がないと思ったので削除しました。
そういう意味があったというのを知りませんでした。勉強になりました。
というわけで、stripslashes が必要そうなところにはそれを施してみました。

2024-07-29 02:11 UTC, drill-lancer commented
@mthaichi
stripslashes はエスケープには関係がないと思ったので削除しました。
そういう意味があったというのを知りませんでした。勉強になりました。
というわけで、stripslashes が必要そうなところにはそれを施してみました。

2024-07-29 05:05 UTC, kurudrive requested changes

2024-07-29 05:05 UTC, kurudrive commented on inc/call-to-action/package/class-vk-call-to-action.php
> +			return do_blocks( do_shortcode( wp_kses_post( $content ) ) );
@drill-lancer コメントに書いてある通り wp_kses_post でエスケープすると outerブロックが出力するstyle属性を無効化される ので、style 属性が消されないように wp_kses を作るなどして対応してください。

2024-07-29 05:21 UTC, drill-lancer commented
@kurudrive 
ちょっと上にそれっぽい許可条件があったのでそれを元にエスケープしてみました。

2024-07-29 06:26 UTC, mthaichi commented
> @mthaichi stripslashes はエスケープには関係がないと思ったので削除しました。 そういう意味があったというのを知りませんでした。勉強になりました。 というわけで、stripslashes が必要そうなところにはそれを施してみました。

@drill-lancer ありがとうございます！
適切に修正されていると思います。

2024-07-29 06:49 UTC, mthaichi commented
> @drill-lancer ありがとうございます！ 適切に修正されていると思います。

@kurudrive @drill-lancer  あと、XSSとまではいかないので must ではないのですが、
たとえば、連絡先の「電話アイコン」は、HTMLは必要ないので、wp_kses_post ではなく、wp_strip_all_tagsを使うといいかなと思います。

「電話番号」については、太字にしたいとか色をつけたいというニーズがあるので、wp_kses_postで良いかもしれません。

余計なHTMLを許可しているのはあまり印象が良くないので、この機会に修正頂くと良いと思います。

面倒な修正、ありがとうございます！

2024-07-29 07:25 UTC, mthaichi commented
@kurudrive @drill-lancer  "echo $" でプロジェクト全体に全文検索かけて、ひっかかった変数が、入力由来のものであればエスケープをかけるという感じで残りを潰していってよいと思います。

2024-07-29 07:36 UTC, drill-lancer commented
@mthaichi 
> 連絡先の「電話アイコン」は、HTMLは必要ない
i タグで書くものと思って wp_kses_post にしています。

2024-07-29 08:27 UTC, mthaichi commented
> @mthaichi
> 
> > 連絡先の「電話アイコン」は、HTMLは必要ない
> 
> i タグで書くものと思って wp_kses_post にしています。

@drill-lancer なるほど、でもここは fas fa-phone-square とクラス名を書く感じではないでしょうか。
font awesomeで iタグをそのままコピペしても通るようにしてあるのであれば、最低限の wp_kses_postでよいと思いますが、としても、理想を言えば wp_ksesで iタグのみ通るようにすべきところだと思います。

長い目でみても、バリデーションを厳しめにしたほうがいいので、もしHTMLいれる必要がないフィールドは wp_strip_all_tags でHTML全削除したほうが良いと私は思います。ご面倒をおかけしますが（・人・）

2024-07-29 08:32 UTC, kurudrive approved these changes

2024-07-29 08:46 UTC, mthaichi commented
> @mthaichi @drill-lancer アイコンの部分はもともと クラス名入力だけだったものを後から i タグで入力してもらうように仕様変更しているケースもあるので、少なくとも i タグの許可は必要です（・ｗ・

@kurudrive @drill-lancer なるほど、tel_iconだけですが直してみましたー。

2024-07-29 09:22 UTC, mthaichi approved these changes

2024-07-29 09:23 UTC, mthaichi commented
すみません。私このあと用事がございまして、@kurudriveさんが見てOK なら良いと思います。🙏

2024-07-29 10:36 UTC, merged

2024-07-29 10:36 UTC, kurudrive commented
@drill-lancer @mthaichi ありがとうございました！