[ カスタム投稿タイプマネージャー ] 設定から解説記事やベクトレへのリンクを追加
vektor-inc/vk-all-in-one-expansion-unit pull request #1117
Opened 2024-10-24 03:44 UTC by mtdkei

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

#1099 

## どういう変更をしたか？

- カスタム投稿タイプ設定に関する記事やベクトレへのリンクを含む通知やテキストリンクを追加しました。
- 有効化一覧の中にカスタム投稿タイプ設定に関する記事を入れるためにtarget="_blank"にできるように設定を変更しました。(veu-packages.php のarrayに`'target'  => '_blank',`がない場合は、テキストリンククリック後、リンクURLが同一タブで開きます。)
- 管理画面でのヘルプ通知を、サイトの言語設定に基づいて動的に切り替え、日本語設定時にのみ表示されるようにしました。

![image](https://github.com/user-attachments/assets/09f088df-e436-43d8-999d-e0faea578cd5)
![スクリーンショット 2024-10-24 12 08 32](https://github.com/user-attachments/assets/d3fd85a8-e69c-415b-a0de-f963a1b306e3)
![スクリーンショット 2024-10-24 12 08 38](https://github.com/user-attachments/assets/ab17c112-e263-441e-9fea-e72f9dd0f18c)

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

#### ソースコードについて

- [x] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [x] 関数名 / 変数名 / クラス名 / 保存値名 はそれだけで内容が想像できるものになっているか？紛らわしい命名になっていないか？
- [x] 関数名 / 変数名 / クラス名 / 保存値名 は既存のコードの命名規則に沿ったものになっているか？

#### デザイン・UI

- [x] 初見のユーザーが予備知識無しで使っても使いやすいようになっているか？
- [x] 情報意味を考慮した意味グルーピング・余白になっているか？
- [x] アラートの表示など追加した場合は他の同様の表示と同じデザインになっているか？

#### プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。
書いていない場合は書かない理由を記載してください。

- [ ] 書けそうなテストは書いたか？
- [ ] 表示要素が仕様通りに表示されない不具合の修正ではない or 表示要素に関する不具合修正の場合テストは書いたか？

#### その他

- [x] readme.txt に変更内容は書いたか？
- [ ] Files changed (変更ファイル)の内容は目視でちゃんと確認したか？
- [ ] このチェック項目を機械的にチェックするのではなく本当にちゃんと確認をしたか？
- [ ] レビュワーが確認しないでリリースしてしまっても問題ないレベルまでちゃんと作りこみ・確認をしたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

- ダッシュボードから ExUnit > 有効化 > カスタム投稿タイプマネージャーに「Learm more」が追加されていること&Learm moreをクリックすると別タブで https://ex-unit.nagoya/ja/about/custom_post_type_manager が表示されることを確認。
- カスタム投稿タイプ設定やカスタム投稿タイプ設定で新規に追加したカスタム投稿タイプの編集画面で、「Help and Documentation」のヘルプ通知ボックスが表示されていることを確認。
- Help and Documentationの中のリンクが以下と同じかを確認。
1. ExUnit サイト：[カスタム投稿タイプマネージャー](https://ex-unit.nagoya/ja/about/custom_post_type_manager)
2. ベクトレ：[X-T9 設定ガイド カスタム投稿タイプ編](https://training.vektor-inc.co.jp/courses/x-t9-custom-post-type/)
3. ベクトレ：[Lightning 基本設定解説 カスタム投稿タイプの設定](https://training.vektor-inc.co.jp/courses/lightning-basic-settings/lessons/lightning-custom-post-type-lightning/)
- 右上のxや通知を無視をクリックすると表示されなくなることを確認。(xの時はページを再読み込みするとヘルプ通知が表示されます。)

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーの確認方法・確認する内容など

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2024-10-25 01:12 UTC, drill-lancer commented
@mtdkei 
実装ありがとうございます。
「通知無視」を押しても通知が消えないような気がします。
URL に vkblocks-dismiss-pro=dismiss_admin_notice が追加されているみたいです。

2024-10-25 01:56 UTC, mtdkei commented
@drill-lancer 
ありがとうございます。うまく通知の無視フラグを保存できてなかったです。
ただいま修正しましたので今一度ご確認いただけたらと思います。

2024-10-28 00:56 UTC, drill-lancer commented
@mtdkei 
なぜ ExUnit なのに vkblocks-dismiss-pro なのか謎は残りますが動作自体は問題ないので承認します。

2024-10-28 01:48 UTC, kurudrive commented
@drill-lancer 

> 謎は残りますが動作自体は問題ないので承認します。

|￣￣￣￣────￣￣￣￣）工数かけてレビューしてるのでせっかく気づいたんですから普通に「これ不自然じゃない？」って言ってください！気づくのは素晴らしい事デス。

2024-10-28 01:50 UTC, mtdkei commented
@drill-lancer @kurudrive 
確かにExUnitですからおかしいですね。
見直してみます。

2024-10-28 02:09 UTC, mtdkei commented
ExUnitのところを途中からVK Blocks Proと勘違いしておりましてお手数をおかけいたしました。
ただいま直しました。

2024-10-28 03:48 UTC, kurudrive requested changes

2024-10-28 03:48 UTC, kurudrive commented on admin/admin-active-setting-page.php
> +					<?php echo ( isset( $att['target'] ) && $att['target'] === '_blank' ) ? 'target="_blank"' : ''; ?>>
@mtdkei 
あー、これは「ExUnit の有効化設定画面で別ウィンドウで開く設定を追加」で趣旨が少し異なるので、微妙なラインですが別のプルリクであげて欲しいですー。で、多分こういう変更は作業中に発生してすぐに承認して欲しい時が多いと思うので、別でプルリクだけ作って、説明とかは適当で良いので、優先ですぐ見て欲しいとか連絡いただけるといいかなとー。
（今回はこのままでいいですー🙂）

2024-10-28 03:48 UTC, kurudrive commented on inc/post-type-manager/package/class.post-type-manager.php
> +			}
@mtdkei Cc: @drill-lancer 

表示するかしないかを判定するメソッドとして、現状の display_help_notice() の中の内容と統合するなどして、
表示するかしないか、と表示する内容のメソッドは分けた方がいいかなと思います。
そうするとテストが書きやすいので。

そして、bool 値を返すメソッドを作るなら is_display_help_notice() みたいに is_ ではじまる方がわかりやすいかな

2024-10-28 03:49 UTC, mtdkei commented on admin/admin-active-setting-page.php
> +					<?php echo ( isset( $att['target'] ) && $att['target'] === '_blank' ) ? 'target="_blank"' : ''; ?>>
そうですね、おっしゃる通りです。次から別のプルリクで対応します。

2024-10-28 03:50 UTC, mtdkei commented on inc/post-type-manager/package/class.post-type-manager.php
> +			}
ありがとうございます。改めて修正してみます。

2024-10-28 05:32 UTC, mtdkei commented on inc/post-type-manager/package/class.post-type-manager.php
> +			}
@kurudrive 
判定するメソッドと表示する内容を分けてみました。管理画面でも日本語のみで表示され、通知を無視をクリックすると再読み込みしたも通知が表示されなくなることを確認しました。
判定の際の関数はis_がつくとその意図がわかりやすいとのこと、確かに勉強になりました。ありがとうございます。

2024-10-28 06:56 UTC, kurudrive commented on inc/post-type-manager/package/class.post-type-manager.php
> +			}
@mtdkei おや？

```
			// サイトの言語が日本語 (ja) であるかどうかを判定
			if ( get_locale() !== 'ja' ) {
				return ''; // 日本語以外の場合は何も返さない
			}

			// ユーザーが通知を無視したフラグが保存されているかをチェック
			if ( get_user_meta( get_current_user_id(), 'vk-all-in-one-expansion-unit_dismissed_notice', true ) ) {
				return ''; // 通知を無視している場合は何も返さない
			}
```
の部分の判定処理は is_display_help_notice() の中に移動でいいんじゃないかなと
思いましたがどうでしょう（・ｗ・？

2024-10-28 07:28 UTC, mtdkei commented on inc/post-type-manager/package/class.post-type-manager.php
> +			}
@kurudrive 
すみません、そのチェックを取り込むのが抜けていました。is_に取り込みました。日本語サイトのみ表示され、通知を無視をクリックすると表示されなくなることを確認しました。

2024-10-28 12:17 UTC, kurudrive commented on inc/post-type-manager/package/class.post-type-manager.php
> +			}
@mtdkei ありがとうございます！

おや...

心なしかプッシュされていない空気を感じます（・ｗ・；

2024-10-28 23:56 UTC, mtdkei commented on inc/post-type-manager/package/class.post-type-manager.php
> +			}
すみません、プッシュミスでした。先ほドプッシュしました。

2024-10-31 13:45 UTC, kurudrive approved these changes

2024-10-31 14:06 UTC, kurudrive commented
@mtdkei ありがとうございます。

本来なら VK_Post_Type_Manager::is_display_help_notice() のテストを書くところですが...まぁ本質的な機能の部分ではないからスキップでいいかな...

という事でマージしますん。

2024-10-31 14:07 UTC, merged