Facebook の SNS アイコンを修正
vektor-inc/vk-all-in-one-expansion-unit pull request #660
Opened 2021-05-12 01:42 UTC by drill-lancer

【変更点】
・Facebook の アイコンを最新のものに変えました。

---

【確認事項】
・ソーシャルボタンのアイコンが正常に反映されているか
・FontAwesome となにかしらの競合を競合していないか

---

icomoon で全体を再編集したり Unicode に割り当てる番号を変えたりする必要があったので仕様変更に等しいのでi
@kurudrive さんに確認を振らせていただきます。

（↑マニュアル整備したほうが良いかもしれません。）

2021-05-26 07:06 UTC, miminari requested changes
@drill-lancer 確認遅くなりました。
こちらですが、EPSが提供されているので、そちらからSVGに変換したものを作成しましたので以下をご利用ください。

`<svg width="520" height="520" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M520 260C520 116.4 403.6 0 260 0S0 116.4 0 260c0 129.77 95.08 237.34 219.38 256.84V335.16h-66.02V260h66.01v-57.28c0-65.16 38.82-101.16 98.21-101.16 28.45 0 58.2 5.08 58.2 5.08v63.98H343c-32.3 0-42.38 20.05-42.38 40.61V260h72.11l-11.52 75.16h-60.58v181.68C424.93 497.34 520 389.77 520 260z" fill="#1877F2"/><path d="M361.2 335.16L372.74 260h-72.1v-48.77c0-20.56 10.07-40.6 42.37-40.6h32.78v-63.99s-29.75-5.08-58.2-5.08c-59.39 0-98.2 36-98.2 101.16V260h-66.02v75.16h66.01v181.68a261.94 261.94 0 0081.25 0V335.16h60.59z" fill="#fff"/></svg>`

2021-05-26 07:13 UTC, drill-lancer commented
@miminari 
白黒の単色にすることは可能ですか？下記警告が表示されるので
```
Multicolor glyphs take more than one character code and cannot have ligatures.
```

2021-05-26 07:18 UTC, miminari commented
@drill-lancer はい！白黒バージョン貼ります！

`<svg width="64" height="64" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M0 32.18A32.38 32.38 0 0026.67 64V40.89h-8V32h8v-7.11c0-8 5.15-12.44 12.44-12.44 2.31 0 4.8.35 7.11.7v8.18h-4.09c-3.9 0-4.8 1.96-4.8 4.45V32h8.54l-1.42 8.89h-7.12V64A32.38 32.38 0 0064 32.18C64 14.48 49.6 0 32 0S0 14.48 0 32.18z" fill="#000"/></svg>`

2021-05-26 07:32 UTC, drill-lancer commented
@miminari 
アイコン変更しておきました！

2021-05-27 23:23 UTC, miminari commented
私にチェックできるのはココまでの気がします。

> icomoon で全体を再編集したり Unicode に割り当てる番号を変えたりする必要があったので仕様変更に等しい

という部分に @kurudrive さんのジャッジが必要そうなのでお願いします。

2021-05-27 23:25 UTC, miminari approved these changes

2021-06-01 01:50 UTC, merged