【確認待ち】有効化設定の初期設定がブロックテーマの場合ブロックテーマ用の設定になるように
vektor-inc/vk-all-in-one-expansion-unit pull request #842
Opened 2022-08-22 07:39 UTC by drill-lancer

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/835

## どういう変更をしたか？

- 有効化設定の初期設定がブロックテーマの場合ブロックテーマ用の設定になるようにしました

## レビューに回す前に確認する事

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

- wp-env 環境で npx wp-env destroy 後に npx wp-env start を実行してから ExUnit > 有効化設定を確認しました
- その後 WordPress のバージョンを 5.8.4 にしてから同様に確認しました

## 確認URL

wp-env 環境で npx wp-env destroy 後に npx wp-env start を実行した環境

## レビュワーの確認方法・確認する内容など

- wp-env 環境で npx wp-env destroy 後に npx wp-env start を実行してから ExUnit > 有効化設定を確認
- その後 WordPress のバージョンを 5.8.4 にしてから同様に確認

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2022-08-22 09:02 UTC, kurudrive commented
@drill-lancer ありがとうございます。
veu_get_packages()  の PHPUnitテストを追加してください。

2022-08-23 01:28 UTC, drill-lancer commented
@kurudrive 
veu_get_packages() はテスト結果の配列が長いので
veu_get_common_options() か veu_get_common_options_default()あたりが妥当なように思えますがいかがでしょうか？

2022-08-23 01:36 UTC, kurudrive commented
@drill-lancer veu_get_common_options() だとブロックテーマかそうじゃない時かの
挙動のテストにならなくないですか（・ｗ・？

2022-08-23 01:39 UTC, kurudrive commented
今回の変更は ブロックテーマの時とそうじゃない場合の初期で有効化される機能の切り替えなので、
それがテスト出来ればOKです。

2022-08-23 04:16 UTC, drill-lancer commented
@kurudrive 
テスト追加しました

2022-08-25 07:14 UTC, kurudrive requested changes

2022-08-25 07:14 UTC, kurudrive commented on tests/test-get-common-options-default.php
> +	 */
@drill-lancer このコメントは多分チガウ空気を感じます...（・ｗ・

2022-08-25 07:14 UTC, kurudrive commented on tests/test-get-common-options-default.php
> + * Class VeuGetPackage
@drill-lancer このコメントは多分チガウ空気を感じます...（・ｗ・

2022-08-25 07:14 UTC, kurudrive commented on tests/test-get-common-options-default.php
> + * Class VeuGetPackage
```suggestion
 * Class VeuGetCommonOptionsDefaultTest
```

2022-08-25 07:14 UTC, kurudrive commented on tests/test-get-common-options-default.php
> +	 */
```suggestion
	/**
	 * クラシックテーマとブロックテーマでの初期値テスト
	 */
```

2022-08-25 07:16 UTC, kurudrive commented
@drill-lancer あーりーがーとーうーございましたたたたーん！

2022-08-25 07:16 UTC, merged