【確認待ち】投稿ページに著者情報の構造化データを出力する機能を追加
vektor-inc/vk-all-in-one-expansion-unit pull request #846
Opened 2022-08-26 04:45 UTC by doshimaf

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

## どういう変更をしたか？

* ユーザー編集ページに@typeとsameAsの設定項目を追加
* 投稿ページに、著者情報の構造化データを出力をJSON-LDで出力

## レビューに回す前に確認する事

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

以下、レビュー確認方法同様です。

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーの確認方法・確認する内容など

* ユーザー編集ページに@typeとsameAsが追加されており、編集・更新ができるか
* 投稿ページのコードを確認し、headに著者情報の構造化データが設定したとおりに出力されているか
* リッチリザルトテストで記事内の構造化データの判定が正常か

リッチリザルトテスト
https://search.google.com/test/rich-results

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2022-08-26 05:46 UTC, kurudrive commented
@drill-lancer これのレビューがあるよ！

2022-08-26 06:04 UTC, drill-lancer commented
@kurudrive 
僕のアドバイス通りに仕上がっていることを確認しましたが、
石川さんの思惑通りかどうかは不明なので石川さんもレビューお願いします。

2022-08-26 06:04 UTC, drill-lancer approved these changes

2022-08-26 06:46 UTC, kurudrive commented
@doshimaf @drill-lancer PHPUnit テストを相談の上書いてみてくださいー。

2022-08-26 07:32 UTC, kurudrive commented
- [ ] プロフィールページでの構造化データの設定UIがわかりにくいので改善（２項目以外もまとめて入力できるように）
- [ ] ↑ 未入力の場合はデフォルトから取得できる情報は自動取得して利用する

2022-08-29 06:41 UTC, doshimaf commented
@kurudrive 
著者構造化データの4項目の設定欄を、ユーザー編集画面末尾に構造化データ見出し以下に追加しました。

2022-08-31 06:33 UTC, doshimaf commented
@kurudrive 
構造化データの出力のコードを、<script></script> の内容をそのまま出力する方法から、出力したい情報を配列にもたせて、json形式に変換して出力する方法に変更しています。

現状、改行やインデントが入らないよう flags を指定しています。

まだUnitテストの書き方がわかっていませんが、この方法のほうがテストコードを書きやすいのかなと思いましたがいかがでしょうか。

2022-09-05 01:58 UTC, doshimaf commented
@kurudrive 
Unitiテストについて、組織投稿の場合のテストまで記述してコミットしています。
「個別の投稿ページじゃないページで空で返ってきてるか？」のテストについては、get_author_array() でページの著者情報を配列にして、print_jsonLD_in_head() で個別の投稿ページにのみjson形式で出力しているという仕様上、現在のテスト方法ではできないのではと思い、保留にして一旦コミットしています。

また確認をお願いたします。

2022-09-05 05:52 UTC, doshimaf commented
@kurudrive 

- 構造化データのauthorの部分をget_author_data()という関数を作成し、分けて取得
- publisher項目は必須項目ではないため、とりあえずコメントアウト

上記変更を加えています。

2022-09-07 03:40 UTC, kurudrive requested changes
@doshimaf ありがとうございます。コメント確認して少し調整よろしくお願いいたします。

2022-09-07 03:40 UTC, kurudrive commented on inc/author-structure-data/class-vk-author-structure-data.php
> +	public static function generate_author_array( $author_id = '' ) {
@doshimaf 
値を返す系は get_
エスケープした上で echo する系は the_
で統一したいっす。
```suggestion
	public static function get_generate_author_array( $author_id = '' ) {
```

2022-09-07 03:40 UTC, kurudrive commented on inc/author-structure-data/class-vk-author-structure-data.php
> +	 * ユーザー情報を配列で返す
@doshimaf 
generate_author_array と get_author_data でコメントが同じなので、もう少し内容がわかるようにコメント調整よろしくお願いいたします。

2022-09-07 03:40 UTC, kurudrive commented on tests/test-author-structure.php
> +	function test_get_author_array() {
@doshimaf 
一つの $this->assert***** 毎（チェックする関数・メソッド毎）に function test_***** を分けて書いてください。
複数のテストで同様のデータのセットアップ処理が必要な場合は、セットアップ処理だけわけてメソッドにして、テストメソッドでそれを読み込んでください。

2022-09-07 03:42 UTC, kurudrive commented
@doshimaf 一旦 pull してから作業よろしくお願いいたします。

2022-09-09 05:34 UTC, doshimaf commented on inc/author-structure-data/class-vk-author-structure-data.php
> +	public static function the_author_array_jsonLD() {
著者情報であるauthorの構造化データの配列を返す関数には、get_author_data
著者情報をを含むユーザーの構造化データ全体の配列を返す関数は、get_author_array
get_author_arrayの$author_arrayをエスケープしてechoする関数は、the_author_array_jsonLD
というように変更しましたが、いかがでしょうか？

2022-09-09 05:36 UTC, doshimaf commented
@kurudrive 
確認いただき、ありがとうございます！

2022-09-09 05:36 UTC, doshimaf commented on inc/author-structure-data/class-vk-author-structure-data.php
> +	public static function the_author_array_jsonLD() {
著者情報であるauthorの構造化データの配列を返す関数には、get_author_data
著者情報をを含むユーザーの構造化データ全体の配列を返す関数は、get_author_array
get_author_arrayの$author_arrayをエスケープしてechoする関数は、the_author_array_jsonLD
というように変更しましたが、いかがでしょうか？

2022-09-09 05:39 UTC, doshimaf commented on tests/test-author-structure.php
> +	function test_get_author_data() {
author部分のみの配列に正しくデータが渡されているかどうかのテストを、test_get_author_dataに分けました。

2022-09-18 16:39 UTC, kurudrive requested changes

2022-09-18 16:39 UTC, kurudrive commented on tests/test-author-structure.php
> +					// ),
@doshimaf このコメントアウトしている部分について、どういう理由でコメントアウトしているのか記載しておいてください〜 (￣人￣)

2022-09-20 00:30 UTC, doshimaf commented
- [ ] コメントアウト理由の記載
- [ ] 関数名やファイル名など適宜AuthorからArticleへ変更

2022-09-22 06:13 UTC, kurudrive approved these changes

2022-09-22 06:27 UTC, kurudrive approved these changes

2022-09-22 06:27 UTC, merged

2022-09-22 06:27 UTC, kurudrive commented
@doshimaf マージしました！ありがとうございました！