Fix/post list ancestor/xss
vektor-inc/vk-all-in-one-expansion-unit pull request #904
Opened 2023-01-20 02:17 UTC by drill-lancer

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/902 と同じ現象が Post List Ancestor でも発生する余地があったため

## どういう変更をしたか？

* このプルリクで変更した事を記載してください

* エスケープ処理追加

## レビューに回す前に確認する事

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

- このブランチでアラートがでなくなる、CSSが効かない事を目視で確認

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーの確認方法・確認する内容など

https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/902 の操作をしても

このブランチでアラートがでなくなる、CSSが効かない事を目視で確認

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2023-01-20 06:31 UTC, doshimaf approved these changes
新しいブロックを追加時はアラートが表示されないことを確認しました。
どなたか2人目確認をお願いいたします。

2023-01-20 07:26 UTC, kurudrive requested changes

2023-01-20 07:26 UTC, kurudrive commented on inc/page-list-ancestor/page-list-ancestor.php
> -			$pageList_ancestor_html  = '<section class="veu_pageList_ancestor veu_card '. $classes . '">';
@drill-lancer 
変更前のここのクラス名の 'veu_pageList_ancestor veu_card' が出力されなくなるんじゃない？

2023-01-20 07:36 UTC, drill-lancer commented on inc/page-list-ancestor/page-list-ancestor.php
> -			$pageList_ancestor_html  = '<section class="veu_pageList_ancestor veu_card '. $classes . '">';
@kurudrive 
その部分は57行目に移動しています

2023-01-25 09:09 UTC, kurudrive commented
@drill-lancer テスト用データの作成は下記を参照ください。
https://github.com/vektor-inc/vk-breadcrumb/blob/master/tests/test-vk-breadcrumb.php

※ 「保留」だと話が進まないので、どうすれば良いのか考えて確認してください (￣人￣)

2023-01-27 07:21 UTC, drill-lancer commented
@kurudrive 
テスト追加しました。

2023-02-01 17:34 UTC, kurudrive approved these changes

2023-02-01 17:34 UTC, kurudrive commented on inc/page-list-ancestor/page-list-ancestor.php
> -			$pageList_ancestor_html  = '<section class="veu_pageList_ancestor veu_card '. $classes . '">';
@drill-lancer あー、なるほど、見落としてました！ありがとうございます！

2023-02-01 17:34 UTC, merged

2023-02-01 17:35 UTC, kurudrive commented
@drill-lancer ありがとうございました！