【確認待ち】ブロックを各機能ごとに分離
vektor-inc/vk-all-in-one-expansion-unit pull request #916
Opened 2023-02-01 02:14 UTC by drill-lancer

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

- 該当する機能が有効化されていないのにその機能のブロックが設置できてしまうのを修正

## どういう変更をしたか？

- ブロックは該当する機能が読み込まれていないと配置できないようにしました。
- ブロックの JS は公式の翻訳で行えば OK のような気がするので一旦 language フォルダを削除しました。

## レビューに回す前に確認する事

- [x] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [x] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
⇒ ブロックの有効・無効を本来の形にしただけなのであえて書くべき内容でもないような・・・
- [x] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

- [ ] 書けそうなテストは書いたか？
⇒下記確認事項がエラーなく実行できれば OK なので不要かと ( 既存の PHP Unit で十分かと )

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

１つ１つ機能を有効化・無効化して機能が有効なときのみブロックが使えることを確認しました。

- [x] SNS
- [x] child-page-index
- [x] contact-section
- [x] page-list-ancestor
- [x] sitemap-page
- [x] call-to-action

## 確認URL

ローカル環境

## レビュワーの確認方法・確認する内容など

１つ１つ機能を有効化・無効化して機能が有効なときのみブロックが使えることを確認お願いします。

- [x] SNS
- [x] child-page-index
- [x] contact-section
- [x] page-list-ancestor
- [x] sitemap-page
- [x] call-to-action

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2023-02-01 20:15 UTC, kurudrive commented
@drill-lancer develop マージしたらテストコケるようになっちゃったのでお手数ですが調整よろしくお願いいたしますー！
※本当は僕のしごとのような気もするけど書籍の都合で僕のスケジュールが破綻したから助けて (´；ω；｀)

2023-02-02 00:31 UTC, drill-lancer commented
@kurudrive 
テストを通して置きました。

2023-02-02 01:51 UTC, kurudrive commented
@drill-lancer ありが...Playwriteのテストが落ちるようになってますー。

https://github.com/vektor-inc/vk-all-in-one-expansion-unit/actions/runs/4070041261/jobs/7010530847

CTA未登録時には「No CTA registered.」が表示されないといけないのに Please Select が表示されるようですー。

2023-02-02 01:53 UTC, drill-lancer commented
@kurudrive 
どうやら石川さんが develop ブランチにマージしたときに CTA の index.php がハチャメチャなことになっていて
それについては現在修正中です。

2023-02-02 02:07 UTC, drill-lancer commented
@kurudrive 
簡易的にですが直しておきました。

2023-02-02 03:01 UTC, kurudrive requested changes

2023-02-02 03:01 UTC, kurudrive commented on inc/child-page-index/child-page-index.php
> +			wp_set_script_translations( 'veu-block-child-page-index', 'veu-block' );
@drill-lancer ここって
```suggestion
			wp_set_script_translations( 'veu-block-child-page-index', 'vk-all-in-one-expansion-unit' );
```
じゃなくって？ それともここは veu-block のままでいいの？

2023-02-02 03:07 UTC, drill-lancer commented
@kurudrive 
そのとおりですね。見落としていましたので修正しました。

2023-02-02 04:51 UTC, kurudrive commented
@drill-lancer ありがとうございました！

2023-02-02 04:51 UTC, merged